import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { AppSkeleton } from "@/components/skeletons/AppSkeleton";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pipvaro | Trading automated",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1e2122]`}
      >
        {/* Nur ein Suspense-Fallback um deine Pages – sonst nichts ändern */}
        <Suspense fallback={<AppSkeleton />}>
          <div className="bg-[#3f4bf2] w-full py-2 px-4 text-white">
            <p className="text-sm">
              🚀 Welcome to Pipvaro! Your trading automation starts here. <strong>Since we are currently in beta phase some features may not be available.</strong> We are currently on <strong>Version 0.0.5</strong>
            </p>
          </div>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
